apiVersion: v1
kind: Service
metadata:
  name: sapient-weather-prediction
spec:
  selector:
    app: sapient-weather-prediction
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort